---
- name: Launch OpenStack instance(s)
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - opsta.openstack_launch_instances

- name: Install python2
  hosts: launched_openstack_instances
  gather_facts: no
  become: true
  tasks:
    - name: Configure apt-cacher-ng
      raw: "(test -f /etc/apt/apt.conf.d/11proxy ||
        echo 'Acquire::http::Proxy \"{{ host_preparation_apt_cacher_ng }}\";' >
          /etc/apt/apt.conf.d/11proxy)"
      when: host_preparation_apt_cacher_ng is defined
    - name: Install Python 2
      raw: "python --version || apt-get update && apt-get install -y python"

- name: Deploy service
  hosts: launched_openstack_instances
  connection: local
  gather_facts: no
  serial: 1
  roles:
    - role: opsta.automated_docker
      when: automated_docker_name is defined
